$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
version: 1
name: dev-environment
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
conda_file: dev-conda.yml