trigger:
- main

jobs:
- job: WaitForAzureMLJobCompletion
  displayName: Wait for AzureML Job Completion

  pool: server
  timeoutInMinutes: 0

  dependsOn: SubmitAzureMLJob
  variables: 
    # We are saving the name of azureMl job submitted in previous step to a variable and it will be used as an inut to the AzureML Job Wait task
    azureml_job_name_from_submit_job: $[ dependencies.SubmitAzureMLJob.outputs['submit_azureml_job_task.JOB_NAME'] ] 

  steps:
  - task: AzureMLJobWaitTask@1
    inputs:
      serviceConnection: 'ml-dev-connection'
      resourceGroupName: $(RESOURCEGROUP)
      azureMLWorkspaceName: $(WORKSPACENAME)
      azureMLJobName: $(azureml_job_name_from_submit_job)
      inlineScript: 'echo Current Job: $JOB_NAME'
